# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/4ndrexyz"

[social.params]
icon = "brand-github"
newtab = true

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/4ndrexyz_"

[social.params]
icon = "brand-twitter"
newtab = true
